const times = [
  // Remember this needs to match with css grid layout
  'SA11:11',
  'SA11:30',
  'SA12:00',
  'SA12:30',
  'SA13:00',
  'SA13:30',
  'SA14:00',
  'SA14:30',
  'SA15:00',
  'SA15:30',
  'SA16:00',
  'SA16:30',
  'SA17:00',
  'SA17:30',
  'SA18:00',
  'SA18:30',
  'SA19:00',
  'SA19:30',
  'SA20:00',
  'SA20:30',
  'SA21:00',
  'SA21:30',
  'SA22:00',
  'SA22:30',
  'SA23:00',
  'SA23:30',
  'SA23:23',
  'SU24:00',
  'SU24:30',
  'SU1:00',
  'SU1:30',
  'SU2:00',
  'SU2:30',
  'SU3:00',
  'SU3:30',
  'SU4:00',
  'SU4:30',
  'SU5:00',
  'SU5:30',
  'SU6:00',
  'SU6:30',
  'SU7:00',
  'SU7:30',
  'SU8:00',
  'SU8:30',
  'SU9:00',
  'SU9:30',
  'SU10:00',
  'SU10:30',
  'SU11:00',
  'SU11:30',
  'SU12:00',
  'SU12:30',
  'SU13:00',
  'SU13:30',
  'SU14:00',
  'SU14:30',
  'SU15:00',
  'SU15:30',
  'SU16:00',
  'SU16:30',
  'SU17:00',
  'SU17:30',
  'SU18:00',
];

// mars => general event
// saturn => workshop
// jupiter => other

const events = [
  {
    name: 'Opening Ceremony',
    subText: '',
    stage: 'mars', // ie colour,
    start: 'SA1130',
    end: 'SA1130',
    length: 4,
  },
  {
    name: 'Hacking Starts',
    subText: '',
    stage: 'mars',
    start: 'SA1200',
    end: 'SA1200',
    length: 2,
  },
  {
    name: 'Intro To Python',
    subText: 'Ethan Guo',
    stage: 'saturn',
    start: 'SA1200',
    end: 'SA1230',
    length: 2,
  },
  {
    name: 'Intro to HTML/CSS',
    subText: 'Andrew Wang + Patrick He',
    stage: 'saturn',
    start: 'SA1300',
    end: 'SA1330',
    length: 2,
  },
  {
    name: 'Product Management',
    subText: 'Andy Tran + Ananya',
    stage: 'venus',
    start: 'SA1300',
    end: 'SA1330',
    length: 2,
  },
  {
    name: 'Intro to API',
    subText: 'Gabby Chan',
    stage: 'venus',
    start: 'SA1400',
    end: 'SA1430',
    length: 2,
  },
  {
    name: 'Bot Prevention with Cryptographically Hard Problems',
    subText: 'Jason Liu',
    stage: 'saturn',
    start: 'SA1400',
    end: 'SA1430',
    length: 2,
  },
  {
    name: 'Intro To Git',
    subText: 'Leon Fattakov',
    stage: 'saturn',
    start: 'SA1500',
    end: 'SA1530',
    length: 4,
  },
  {
    name: 'Coding Realistic Physics Simulations',
    subText: 'Jason Schattman',
    stage: 'venus',
    start: 'SA1600',
    end: 'SA1630',
    length: 2,
  },
  {
    name: 'Making and Monetizing Side Projects',
    subText: 'Chris Sev',
    stage: 'saturn',
    start: 'SA1600',
    end: 'SA1630',
    length: 2,
  },
  {
    name: 'Quantum Science: From Philosophy to Technology',
    subText: 'John Donohue',
    stage: 'saturn',
    start: 'SA1700',
    end: 'SA1730',
    length: 2,
  },
  {
    name: 'Build on Ethereum with scaffold-eth',
    subText: 'Austin Griffith',
    stage: 'venus',
    start: 'SA1700',
    end: 'SA1730',
    length: 2,
  },
  {
    name: 'React Fundamentals + Building a Netflix Clone',
    subText: 'Steven Xu',
    stage: 'saturn',
    start: 'SA1800',
    end: 'SA1830',
    length: 4,
  },
  {
    name: 'How to Build a Cloud-Connected AR App',
    subText: 'echoAR',
    stage: 'venus',
    start: 'SA1900',
    end: 'SA1930',
    length: 2,
  },
  {
    name: 'Quick Draw Emoji with Machine Learning',
    subText: 'Makeschool',
    stage: 'saturn',
    start: 'SA1900',
    end: 'SA1930',
    length: 2,
  },
  {
    name: 'Panel: Pursuing a Career in Tech - What You Need To Know',
    subText: '',
    stage: 'jupiter',
    start: 'SA2000',
    end: 'SA2030',
    length: 4,
  },
  {
    name: 'Meetup: Grade 12 Hackers',
    subText: '',
    stage: 'jupiter',
    start: 'SA2100',
    end: 'SA2130',
    length: 4,
  },
  {
    name: 'Minecraft Build Tourney',
    subText: '',
    stage: 'jupiter',
    start: 'SA2200',
    end: 'SA2230',
    length: 4,
  },
  {
    name: 'Brain Break! Origami Crane',
    subText: '',
    stage: 'jupiter',
    start: 'SA2300',
    end: 'SA2330',
    length: 4,
  },
  {
    name: 'Skribbl.io',
    subText: '',
    stage: 'jupiter',
    start: 'SU2400',
    end: 'SU2430',
    length: 4,
  },
  {
    name: 'Minecraft Minigames',
    subText: '',
    stage: 'jupiter',
    start: 'SU200',
    end: 'SU330',
    length: 4,
  },
  {
    name: 'Bedtime Story Reading',
    subText: '',
    stage: 'jupiter',
    start: 'SU400',
    end: 'SU430',
    length: 4,
  },
  {
    name: 'Kahoot',
    subText: '',
    stage: 'jupiter',
    start: 'SU800',
    end: 'SU830',
    length: 4,
  },
  {
    name: 'Meetup: Hacker Debrief',
    subText: '',
    stage: 'jupiter',
    start: 'SU900',
    end: 'SU930',
    length: 4,
  },
  {
    name: 'How To Pitch Your Hackathon Project',
    subText: 'Advait Maybhate',
    stage: 'saturn',
    start: 'SU1000',
    end: 'SU1030',
    length: 4,
  },
  {
    name: 'Hacking Ends',
    subText: '',
    stage: 'mars',
    start: 'SU1200',
    end: 'SU1200',
    length: 4,
  },
  {
    name: 'Pitch times released',
    subText: '',
    stage: 'mars',
    start: 'SU1300',
    end: 'SU1300',
    length: 4,
  },
  {
    name: 'Live Pitching',
    subText: '',
    stage: 'mars',
    start: 'SU1330',
    end: 'SU1500',
    length: 4,
  },
  {
    name: 'Closing Ceremony',
    subText: '',
    stage: 'mars',
    start: 'SU1800',
    end: 'SU1800',
    length: 4,
  },
];

export { times, events };
